### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by zhengzetao1** [chn-lee-yumi/MaterialSearch#105]
Traceback (most recent call last):
  File "E:\MaterialSearch_tmp\MaterialSearchWindows\main.py", line 13, in <module>
    from process_assets import match_text_and_image, process_image, process_text
  File "E:\MaterialSearch_tmp\MaterialSearchWindows\process_assets.py", line 9, in <module>
    import torch
  File "E:\MaterialSearch_tmp\MaterialSearchWindows\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "E:\MaterialSearch_tmp\MaterialSearchWindows\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by chn-lee-yumi** [comment]
环境问题请自行解决：https://www.bing.com/search?q=Error+loading+%22site-packages%5Ctorch%5Clib%5Cfbgemm.dll%22+or+one+of+its+dependencies.&qs=n&form=QBRE&sp=-1&lq=0&pq=error+loading+%22site-packages%5Ctorch%5Clib%5Cfbgemm.dll%22+or+one+of+its+dependencies.&sc=6-78&sk=&cvid=7D523135BA15447AAFECDFBFE158862B&ghsh=0&ghacc=0&ghpl=

**Comment by chn-lee-yumi** [comment]
可以参考：https://github.com/pytorch/pytorch/issues/129568

**Comment by chn-lee-yumi** [comment]
最新版本整合包已修复此问题
