### ISSUE TITLE
文字搜图、文字搜视频出现错误 ：ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 768 is different from 512)

### ISSUE THREAD

**Issue by wxbool** [chn-lee-yumi/MaterialSearch#3]
文字搜图、文字搜视频出现错误

```
{'positive': '测试', 'negative': '', 'top_n': '6', 'search_type': 0, 'positive_threshold': 10, 'negative_threshold': 10, 'image_threshold': 85}
[2023-05-09 15:44:48,627] ERROR in app: Exception on /api/match [POST]
Traceback (most recent call last):
  File "G:\ProgramData\Anaconda3\envs\material-search\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\ProgramData\Anaconda3\envs\material-search\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\ProgramData\Anaconda3\envs\material-search\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\ProgramData\Anaconda3\envs\material-search\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ViggoSpace\GoWork\Home\video-make-case-research\python\MaterialSearch\main.py", line 379, in api_match
    sorted_list = search_image(positive_prompt=data['positive'], negative_prompt=data['negative'],
  File "E:\ViggoSpace\GoWork\Home\video-make-case-research\python\MaterialSearch\main.py", line 207, in search_image
    scores = match_batch(positive_feature, negative_feature, image_features, positive_threshold, negative_threshold)
  File "E:\ViggoSpace\GoWork\Home\video-make-case-research\python\MaterialSearch\process_assets.py", line 171, in match_batch
    positive_scores = (new_features @ new_text_positive_feature.T)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 768 is different from 512)
```

**Comment by chn-lee-yumi** [comment]
这个问题的原因应该是你在扫描后更换了配置里面的模型。更换模型需要删库重扫。

openai/clip-vit-base-patch32的输出长度是512

openai/clip-vit-large-patch14的输出长度是768

两个模型输出长度不一样，所以不兼容。

**Comment by chn-lee-yumi** [comment]
感谢反馈，我已经在模型配置那里添加了备注~
