### ISSUE TITLE
启动报错 TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by muxuan1978** [chn-lee-yumi/MaterialSearch#44]
执行python main.py，打印配置后报错：

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from database import get_image_path_by_id, is_video_exist
  File "D:\MaterialSearch\database.py", line 192, in <module>
    def get_image_id_path_features(session: Session) -> tuple[list[int], list[str], list[bytes]]:
TypeError: 'type' object is not subscriptable

**Comment by chn-lee-yumi** [comment]
你的python版本是多少？尝试更新一下。
