### ISSUE TITLE
您好up，想问下这是什么问题呀

### ISSUE THREAD

**Issue by wzyass** [chn-lee-yumi/MaterialSearch#60]
![Uploading 56ed062c9df801ecc337b3bc2b625cc.png…]()

**Comment by wzyass** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\__main__.py", line 2, in <module>
    main()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\cli.py", line 1107, in main
    cli.main()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\cli.py", line 955, in run_command
    raise e from None
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\cli.py", line 939, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\cli.py", line 337, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\cli.py", line 247, in locate_app
    __import__(module_name)
  File "C:\Users\dell\PycharmProjects\clip\MaterialSearch\main.py", line 13, in <module>
    from process_assets import match_text_and_image, process_image, process_text
  File "C:\Users\dell\PycharmProjects\clip\MaterialSearch\process_assets.py", line 17, in <module>
    model = AutoModelForZeroShotImageClassification.from_pretrained(MODEL_NAME).to(torch.device(DEVICE))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\auto\auto_factory.py", line 523, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1138, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\utils\hub.py", line 441, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like OFA-Sys/chinese-clip-vit-base-patch16 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by chn-lee-yumi** [comment]
README.md已有说明：

> 注意，首次运行会自动下载模型。下载速度可能比较慢，请耐心等待。如果网络不好，模型可能会下载失败，这个时候重新执行程序即可。

**Comment by wzyass** [comment]
> README.md已有说明：
> 
> > 注意，首次运行会自动下载模型。下载速度可能比较慢，请耐心等待。如果网络不好，模型可能会下载失败，这个时候重新执行程序即可。

您好up，这边是需要挂个梯子么还是租一个服务器能解决呢

**Comment by chn-lee-yumi** [comment]
> > README.md已有说明：
> > > 注意，首次运行会自动下载模型。下载速度可能比较慢，请耐心等待。如果网络不好，模型可能会下载失败，这个时候重新执行程序即可。
> 
> 您好up，这边是需要挂个梯子么还是租一个服务器能解决呢

这个需要多做好人好事攒人品，就可以解决。

或者你用整合包：https://pan.baidu.com/s/1jtJOoYNs3oVgFTckg7G5Qw?pwd=CHNL
