### ISSUE TITLE
关于开启cuda 运行报错的问题

### ISSUE THREAD

**Issue by jianhudiyi** [chn-lee-yumi/MaterialSearch#77]
**### 本地环境如下：本地环境：**
显卡是3060ti  16g，Win11，已科学上网，pytorch和cuda的版本都是12.1  

### 运行run.bat报错：
Traceback (most recent call last):
  File "E:\MaterialSearchWindows\MaterialSearchWindows\main.py", line 13, in <module>
    from process_assets import match_text_and_image, process_image, process_text
  File "E:\MaterialSearchWindows\MaterialSearchWindows\process_assets.py", line 18, in <module>
    model = AutoModelForZeroShotImageClassification.from_pretrained(MODEL_NAME).to(torch.device(DEVICE))
  File "E:\MaterialSearchWindows\MaterialSearchWindows\lib\site-packages\transformers\modeling_utils.py", line 2724, in to
    return super().to(*args, **kwargs)
  File "E:\MaterialSearchWindows\MaterialSearchWindows\lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
  File "E:\MaterialSearchWindows\MaterialSearchWindows\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "E:\MaterialSearchWindows\MaterialSearchWindows\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "E:\MaterialSearchWindows\MaterialSearchWindows\lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "E:\MaterialSearchWindows\MaterialSearchWindows\lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
  File "E:\MaterialSearchWindows\MaterialSearchWindows\lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
  File "E:\MaterialSearchWindows\MaterialSearchWindows\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

### 已经尝试的排错
**.evn文件配置**
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/162315614/d27167d9-6a2d-4176-9dcd-2a8dc3c83e6f)

**验证PyTorch是否正确导入 是否支持CUDA**
import torch  
print(torch.__version__)  
print(torch.cuda.is_available())  
input("Press Enter to continue...")

输出结果如下，是没问题的
2.3.1+cu121
True
Press Enter to continue...

**关于pytorch和cuda的版本（都是12.1）**
![image](https://github.com/chn-lee-yumi/MaterialSearch/assets/162315614/9ce760a6-c612-4096-99e6-edbdeee4769d)

### 查看电脑上安装的所有包，排查是否有安装重复的pytorch包（只有一个pytorch包）
Package                Version
---------------------- ------------
blinker                1.8.2
certifi                2024.2.2
charset-normalizer     3.3.2
click                  8.1.7
colorama               0.4.6
filelock               3.14.0
fsspec                 2024.5.0
greenlet               3.0.3
idna                   3.7
intel-openmp           2021.4.0
itsdangerous           2.2.0
Jinja2                 3.1.4
MarkupSafe             2.1.5
mkl                    2021.4.0
mpmath                 1.3.0
networkx               3.3
numpy                  1.26.4
opencv-python-headless 4.9.0.80
packaging              24.0
pillow                 10.3.0
pillow_heif            0.16.0
pip                    24.0
python-dotenv          1.0.1
PyYAML                 6.0.1
regex                  2024.5.15
requests               2.32.3
safetensors            0.4.3
SQLAlchemy             2.0.30
sympy                  1.12.1
tbb                    2021.12.0
torch                  2.3.1+cu121
torchaudio             2.3.1+cu121
torchvision            0.18.1+cu121
tqdm                   4.66.4
typing_extensions      4.12.0
urllib3                2.2.1
Werkzeug               3.0.3

**Comment by chn-lee-yumi** [comment]
你的排错过程用的是本机的python环境，而不是整合包内的python环境。你是否已经根据说明执行了`CUDA加速安装.bat`？

**Comment by chn-lee-yumi** [comment]
我发现`CUDA加速安装.bat`存在bug，新版本已修复。你可以直接修改这个文件，把`install`改成`install -U`，重新运行即可。
